---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - server/

commonLabels:
  app.kubernetes.io/name: event-forwarder

images:
  - name: event-forwarder
    newName: xingse/event-forwarder-gelf
    newTag: "v1.1.0"

...
