---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: event-forwarder
  labels:
    app.kubernetes.io/name: event-forwarder
    app.kubernetes.io/component: server

rules:
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "get"
      - "watch"
      - "list"

...
