---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole

metadata:
  name: event-forwarder

rules:
  - apiGroups:
      - ""
    resources:
      - "events"
    verbs:
      - "get"
      - "watch"
      - "list"

...
