---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: event-forwarder
  labels:
    app.kubernetes.io/name: event-forwarder
    app.kubernetes.io/component: server

spec:
  replicas: 1
  revisionHistoryLimit: 3

  strategy:
    type: Recreate

  selector:
    matchLabels:
      app.kubernetes.io/name: event-forwarder
      app.kubernetes.io/component: server

  template:
    metadata:
      labels:
        app.kubernetes.io/name: event-forwarder
        app.kubernetes.io/component: server

    spec:
      enableServiceLinks: false
      serviceAccountName: event-forwarder

      containers:
        - name: server
          image: event-forwarder
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsUser: 65534
            readOnlyRootFilesystem: true

          envFrom:
            - configMapRef:
                name: event-forwarder

          resources:
            requests:
              cpu: "0.1"
              memory: "128Mi"
            limits:
              cpu: "1.0"
              memory: "128Mi"

...
