---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - serviceaccount.yml
  - clusterrole.yml
  - clusterrolebinding.yml
  - deployment.yml

configMapGenerator:
  - name: event-forwarder
    options:
      labels:
        app.kubernetes.io/name: event-forwarder
        app.kubernetes.io/component: server
    literals: []

...
